### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by ThePHOENlX** [Keee03/SMP-Net#1]
您好，我是VIPL的李鑫，目前也在从事人脸心率测量方向工作
请问数据预处理时，PPG_Signal是如何与STMap以及STMap——infrared对齐的呢？
这一块代码load也没有太理解
![捕获](https://user-images.githubusercontent.com/49563121/222666438-bf0172c2-95b2-4cd7-813e-324dc75ad85b.PNG)
谢谢解答！！

**Comment by Keee03** [comment]
是这样的，我们设计了一套软件系统，这套系统可以控制我们的可见光视频、红外视频和指夹式血氧仪的PPG信号同步开始采集和结束，所以我们每一组数据在时间上是对应的（同时开始和结束），无需再做处理。
在预处理部分，我会把每个视频的完整时空图计算并保存，也就是说，对于一个可见光视频(60s,25FPS)，我会得到一个(276,1500,3)尺寸的时空图，红外视频同理。然后在取用的时候按照滑动窗口(长度为10s，步长为2)的方式一组一组的取。
PPG信号的采样率是60Hz，10秒钟数据对应的信号长度为(600,)，然后将其重新采样至和时空图的长度相等(250,)，最为我们的标签。
